### PR TITLE
Added OTEL for tracing, metrics, logging (Console and OTLP exporters)

### PR DESCRIPTION
**Pull request by napalm684**
Foundation for https://github.com/FritzAndFriends/TagzApp/issues/136

Added [Grafana](https://grafana.com/grafana/) setup utilizing [Tempo](https://grafana.com/oss/tempo/) for tracing (backed by Prometheus), [Prometheus](https://prometheus.io/) for metrics and [Loki](https://grafana.com/oss/loki/) for logging. Enabled features to correlate traces, metrics and logs within Grafana. All services added to:

https://github.com/FritzAndFriends/TagzApp/blob/a1fdd75f314bbcee7d6d10ccafa278ec6545a548/docker-compose.local.yml

until @csharpfritz figures out what he wants to do with them going forward. Simply run `docker compose -f ./docker-compose.local.yml up` and the observability service stack will spin up. Run TagzApp.Blazor pointed at otlp exporter for traces, logs and metrics and let OTEL collector forward to the appropriate places/formats.

Note: The newly announced .NET 8 dashboards are pre-installed and wired up to prometheus (see here):

https://devblogs.microsoft.com/dotnet/introducing-aspnetcore-metrics-and-grafana-dashboards-in-dotnet-8/

### CODE REVIEW

**Comment by napalm684** [comment]
Started a blog post series related to this work. Part 1 up - https://shawn.vause.us/posts/opentelemetry-dotnet/

**Comment by napalm684** [comment]
Logs are here @csharpfritz 
image

Something doesn't seem to be working though with the trace to logs feature I will have to look into that. You should be able to explore the tempo traces and have a link on the trace/span to jump to logs.

**Comment by napalm684** [comment]
Scratch that it is here:
image

**Comment by napalm684** [comment]
@csharpfritz what would you like to see so we can get this merged up?

**Comment by csharpfritz** [comment]
Let's put together some samples around creating custom metrics and traces
from the Mastodon provider to show how we can create a custom TagzApp
dashboard and metrics.

This way we can start rolling this work through the rest of the application

Thoughts?

Jeff

**Comment by napalm684** [comment]
Initial Dashboard:
image

**Pull request merged**
