### PR TITLE
Feature code style check GitHub Action

### PR DESCRIPTION
**Pull request by degenone**
After a few alterations to the my suggested GitHub Action, it should now work properly.

I also ran `npx prettier` on all `.js` and `.css` files not in a `/lib/` folder.

### CODE REVIEW

**Comment by degenone** [comment]
I believe the problem is that since `dotnet format` is ran on `ubuntu-latest` it does not like Windows new lines.

Could be fixed with changing it to `windows-latest` but that seems to increase the time the job takes by quite the bit.

Is there a better fix? I tried Googling but to no avail.

**Comment by csharpfritz** [comment]
Looks like a good patch...  one request:  can we have the code formatting run first and have the Build and Test .NET project tasks run after the code cleanup?  

Let's have the Build and Test actions depend on the code formatting job

**Comment by csharpfritz** [comment]
Also:  this doesn't look like its updating the files in the repository when its done formatting them.  

I think we want this only running when a pull-request is opened, and then update the source files in the remote repository so that we know they match our format when they're eventually merged

**Comment by degenone** [comment]
> Also: this doesn't look like its updating the files in the repository when its done formatting them.

I touched on this in the issue that the idea was to make a "checker" rather than a "formatter" but I can work on it.

One thing I noticed while testing is that `dotnet format` doesn't like to fix naming rule violations:

```powershell
> dotnet format .\src\TagzApp.sln --include .\src\TagzApp.Web\Pages\Error.cshtml.cs
Unable to fix IDE1006. Code fix NamingStyleCodeFixProvider doesn't support Fix All in Solution.
```

**Pull request closed without merging**
