### PR TITLE
Feature code formatter action

### PR DESCRIPTION
**Pull request by degenone**
Syncing the branch through GitHub seems to have closed the last PR.

In the action, I add to `.editorconfig`:
- [Remove unnecessary using directives (IDE0005)](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0005)
- [this and Me preferences (IDE0003 and IDE0009)](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0003-ide0009)
- [Simplify new expression (IDE0090)](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0090)

Are these ok? Are there others we should add?

I also made some minor chore changes to trigger formatting, mostly IDE suggestions, e.g. naming rule violations.

### CODE REVIEW

**Comment by degenone** [comment]
The formatting part of the action is working properly so far.

The `commit` part is causing issues. I'm not sure if it's an issue with which `permissions` it has or something else.

```bash
remote: Permission to FritzAndFriends/TagzApp.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/FritzAndFriends/TagzApp/': The requested URL returned error: 403
```

**Comment by degenone** [comment]
I don't think it's possible to do this the way I'm trying to. But maybe there is another way to achieve the same result or I'm missing something.

Essentially I'm asking a workflow on `FritzAndFriends/TagzApp` to change files in a branch of `<pr-actor>/TagzApp` repo. I can see why GitHub might not want to allow that.

I'm hoping for suggestions or maybe the formatting needs to be done after the merge to main.

**Comment by degenone** [comment]
> To test stuff you basically have to test it in your own (forked) Repo and not forgetting to properly set the target Repo in the workflow to the correct one shortly before the merge.

This has been a case of "works on my repo" for me. When I tested it on my own fork, the PR did get formatted and the action did push to the PR branch correctly but then when I made the PR here I ran into the permissions issues.

**Comment by csharpfritz** [comment]
I like that short list of fixes that are added along with the rest of `.editorConfig` being applied.

**Comment by Stelzi79** [comment]
> > To test stuff you basically have to test it in your own (forked) Repo and not forgetting to properly set the target Repo in the workflow to the correct one shortly before the merge.
> 
> This has been a case of "works on my repo" for me. When I tested it on my own fork, the PR did get formatted and the action did push to the PR branch correctly but then when I made the PR here I ran into the permissions issues.

Yea IMO you want to do "too much" in one single PR. Smaller changes in fewer files are faster to check and merge as a maintainer because they are "less" work to cross all the `i`s and dot the `t`s 😉 There is also one thing you can do to not "litter" the commit logs with merges from `main`. Just rebase your branch to main in order to keep it up to date.

To go forward I would do the following:
- open an Issue in order to track all the different PRs (I haven't seen any linked any Issue for this huge PR)
- open several different PRs of all the whitespace changes on a Project bases or as needed to keep them smallish
- after all the whitespace PRs are merged open one or more PRs of the functional changes and GH Actions in order to enforce all these whitespace changes in the future

**Comment by degenone** [comment]
> Yea IMO you want to do "too much" in one single PR. Smaller changes in fewer files are faster to check and merge as a maintainer because they are "less" work to cross all the `i`s and dot the `t`s 😉

Yeah, in hindsight I was too eager since it worked so well on my fork. Most of it is `dotnet format` or `prettier` doing the work, I did just small changes e.g. conform to Naming Rules (`var logger` => `var _Logger`).

> There is also one thing you can do to not "litter" the commit logs with merges from `main`. Just rebase your branch to main in order to keep it up to date.

This is probably a better way but all I did was resolve conflicts here on GitHub and hopefully all of this gets `Squash and merge`'d in the end.

> I haven't seen any linked Issue for this huge PR

#131 is the issue, I also mention it in couple early commits.

I'm still not quite sure if my [commit step](https://github.com/degenone/TagzApp/blob/feature_code_check_action/.github/workflows/dotnet.yml#L185) or [permissions](https://github.com/degenone/TagzApp/blob/feature_code_check_action/.github/workflows/dotnet.yml#L103) or [checkout-action settings](https://github.com/degenone/TagzApp/blob/feature_code_check_action/.github/workflows/dotnet.yml#L109) are the problem or where the issue lies.

**Comment by degenone** [comment]
Could it be that even though this repo has `Read and write permissions` for `Workflow permissions`, since this is still a PR it only gets read permissions?

image

I might need to redo the PR with just the changes to the Workflow.

**Pull request closed without merging**
