### PR TITLE
Changed Space and Mixed Tabs to Tabs per the .editorconfig File

### LINKED ISSUE #120: Cleanup of mixed tab and space characters throughout the code
Reformat code to meet the .editorconfig files settings for tab usage in the code.

In addition a suggestion of moving the .editorconfig into the root folder to help guide the formatting of the entire solution.

### PR DESCRIPTION
**Pull request by mpaulosky**
Fixes #120

### CODE REVIEW

**Comment by mpaulosky** [comment]
I am confused with these errors I not sure how to trouble shoot this issue!  It would help me to learn some new trouble shooting skills if someone could point me in the right direction!

**Comment by mpaulosky** [comment]
I also apologize I completely spaced running a build locally before pushing to the GitHub.  But found the errors for some reason my VS was adding the required to several fields in the Tweets.cs and the Content.cs files l luckily had Rider available and it was not having that issue and the build was successful

**Comment by mpaulosky** [comment]
I am not sure why the Playwright test failed here they ran to successfully in VS and Rider?

**Comment by csharpfritz** [comment]
Looking at this now...  feels strange...

**Comment by mpaulosky** [comment]
There I go thinking this would be a simple change, shouldn't break anything... Not!

Now I have to figure out why my VS was adding required to fields on it's own.

**Comment by csharpfritz** [comment]
Thank you for following up on this.  I really appreciate these types of clean up tasks that ensure our code is consistent

**Pull request merged**
