### PR TITLE
Feature Code Formatting Action

### LINKED ISSUE #131: Suggestion: Code Style Check GitHub Action
After the Tabs vs Spaces and `.editorconfig` talk on stream I decided to experiment with creating a GitHub Action for code style checking.

Here is what I came up with:

```yml
name: code-style-check
on: pull_request

jobs:

  get-changed-files:
    runs-on: ubuntu-latest
    outputs:
      cs_files: ${{ steps.cs.outputs.cs_files }}
      js_css_files: ${{ steps.js_css.outputs.js_css_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get diff
        run: |
          {
            echo 'diff<<EOF'
            git diff main --name-status
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Assign C# files to output
        id: cs
        run: |
          {
            echo 'cs_files<<EOF'
            echo "$diff" | grep -E "^[ACMR][0-9]{0,3}[[:space:]]+.+\.cs$" | sed -E "s/.*[[:space:]]+//"
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: Assign JS/CSS files to output
        id: js_css
        run: |
          {
            echo 'js_css_files<<EOF'
            echo "$diff" | grep -E "^[ACMR][0-9]{0,3}[[:space:]]+.+\.(js|css)$" | sed -E "s/.*[[:space:]]+//"
            echo EOF
          } >> "$GITHUB_OUTPUT"

  run-dotnet-format:
    if: needs.get-changed-files.outputs.cs_files != ''
    runs-on: ubuntu-latest
    needs: get-changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: dotnet format
        run: dotnet format --verbosity detailed --verify-no-changes --include ${{ needs.get-changed-files.outputs.cs_files }}

  run-prettier:
    if: needs.get-changed-files.outputs.js_css_files != ''
    runs-on: ubuntu-latest
    needs: get-changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write ${{ needs.get-changed-files.outputs.js_css_files }}
          dry: true
```

This will only check the files the PR changed. If we assume that the current files are formatted properly ( #121 ), it would only check the new code in the PR. 

It also includes a job with `Prettier` for `.css` and `.js` checks but this could be dropped.

I'm not sure what would be the best approach with `.cshtml` files.

My version does not actually format the files but it is there to encourage contributors to run `dotnet format` (and maybe `npx prettier`) before their PR.

### PR DESCRIPTION
**Pull request by degenone**
I believe the issue with the last PR was that since it was just a PR, it was not granted full write permissions (which is understandable) and was not able to push the formatting commit.

To showcase the workflow I create `foo_main` -branch on my fork and changed the workflow triggers accordingly and then made a PR to that branch.

1. [the PR](https://github.com/degenone/TagzApp/pull/16)
1. [on pull request workflow run](https://github.com/degenone/TagzApp/actions/runs/6098008511)
1. [on push workflow run](https://github.com/degenone/TagzApp/actions/runs/6098052168)

Closes #131

### CODE REVIEW

**Comment by Stelzi79** [comment]
Please also add a `needs: [code-formatting]` to [todos-to-issues.yml](https://github.com/FritzAndFriends/TagzApp/blob/main/.github/workflows/todos-to-issues.yml). This PR makes a nice addition to this workflow!

**Comment by degenone** [comment]
> Please also add a `needs: [code-formatting]` to [todos-to-issues.yml](https://github.com/FritzAndFriends/TagzApp/blob/main/.github/workflows/todos-to-issues.yml). 

When I add this, my VSCode complains:
```
The workflow must contain at least one job with no dependencies.
Value 'code-formatting' is not valid
```

**Comment by Stelzi79** [comment]
> > Please also add a `needs: [code-formatting]` to [todos-to-issues.yml](https://github.com/FritzAndFriends/TagzApp/blob/main/.github/workflows/todos-to-issues.yml?rgh-link-date=2023-09-06T20%3A43%3A16Z).
> 
> When I add this, my VSCode complains:
> 
> ```
> The workflow must contain at least one job with no dependencies.
> Value 'code-formatting' is not valid
> ```

Hm I thought that works across workflows ... I will investigate that.

**Comment by Stelzi79** [comment]
Please add 
```
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types: 
      - completed
```
in the `on:` section. (See the accepted answer in this [Dependencies Between Workflows on Github Actions](https://stackoverflow.com/questions/58457140/dependencies-between-workflows-on-github-actions) SO question.)

**Comment by csharpfritz** [comment]
Thank you for the research and implementing this...  it helps to keeps us all on a consistent code-style.

**Pull request merged**
